# -*- coding: utf-8 -*-
"""model reliability.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17_jOLg8Gz5Ggm0PV2LXaTxxOEjDY-nty

Task 1: Reproduce and Identify Leakage
"""

from sklearn.datasets import make_classification
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Generate Data
X, y = make_classification(n_samples=1000, n_features=10, random_state=42)

# FLAWED APPROACH: Scale before splitting
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)

print(f"Train Accuracy: {accuracy_score(y_train, model.predict(X_train)):.4f}")
print(f"Test Accuracy: {accuracy_score(y_test, model.predict(X_test)):.4f}")

"""Task 2: Fix the Workflow Using a Pipeline"""

from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score

# Reset data and split FIRST
X, y = make_classification(n_samples=1000, n_features=10, random_state=42)
X_train_raw, X_test_raw, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create Pipeline
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('clf', LogisticRegression())
])

# 5-fold Cross-Validation
cv_scores = cross_val_score(pipeline, X_train_raw, y_train, cv=5)

print(f"CV Mean Accuracy: {cv_scores.mean():.4f}")
print(f"CV Standard Deviation: {cv_scores.std():.4f}")

"""Task 3: Experiment with Decision Tree Depth"""

from sklearn.tree import DecisionTreeClassifier
import pandas as pd

depths = [1, 5, 20]
results = []

for d in depths:
    dt = DecisionTreeClassifier(max_depth=d, random_state=42)
    dt.fit(X_train, y_train)

    train_acc = accuracy_score(y_train, dt.predict(X_train))
    test_acc = accuracy_score(y_test, dt.predict(X_test))

    results.append({"Max Depth": d, "Train Accuracy": train_acc, "Test Accuracy": test_acc})

# Display Table
print(pd.DataFrame(results))