# -*- coding: utf-8 -*-
"""multiple linear regression model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-R0UrdB5ArxKrdyTbnQEeiVxaxGLkFHs
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# --- TASK 1: Dataset & Model ---
np.random.seed(42)
n_samples = 60

area = np.random.randint(800, 3500, n_samples)
bedrooms = np.random.randint(1, 6, n_samples)
age = np.random.randint(0, 30, n_samples)
# Formula: 10 (base) + 0.05*area + 5*beds - 0.5*age + noise
price = 10 + (0.05 * area) + (5 * bedrooms) - (0.5 * age) + np.random.normal(0, 5, n_samples)

df = pd.DataFrame({
    'area_sqft': area,
    'num_bedrooms': bedrooms,
    'age_years': age,
    'price_lakhs': price
})

X = df[['area_sqft', 'num_bedrooms', 'age_years']]
y = df['price_lakhs']

model = LinearRegression()
model.fit(X, y)
predictions = model.predict(X)

print(f"Intercept: {model.intercept_:.2f}")
for feature, coef in zip(X.columns, model.coef_):
    print(f"Coefficient ({feature}): {coef:.4f}")

comparison = pd.DataFrame({'Actual': y, 'Predicted': predictions})
print("\nFirst 5 Actual vs. Predicted:")
print(comparison.head())

# --- TASK 2: Evaluation ---
mae = mean_absolute_error(y, predictions)
rmse = np.sqrt(mean_squared_error(y, predictions))
r2 = r2_score(y, predictions)

print(f"\nMAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R²: {r2:.2f}")

"""
Interpretation:
MAE shows the average absolute error (off by ~X lakhs).
RMSE penalizes larger errors more than MAE.
R² tells us what percentage of price variance is explained by our features.
"""

# --- TASK 3: Residuals ---
residuals = y - predictions

plt.figure(figsize=(8, 5))
plt.hist(residuals, bins=15, color='skyblue', edgecolor='black')
plt.title('Distribution of Residuals')
plt.xlabel('Residual (Error)')
plt.ylabel('Frequency')
plt.show()